### ISSUE TITLE
Please add new requirement of scipy<1.13.0 to this package

### ISSUE THREAD

**Issue by coleslaw481** [idekerlab/cellmaps_ppi_embedding#4]
Due to removal of `scipy.linalg.triu` from scipy in version 1.12.0 please add this
restriction of scipy version to `requirements.txt` and `setup.py`

`scipy<1.13.0`

node2vec uses the above library and that maintainer is no longer making fixes. This change breaks for versions of python 3.9 and above

**Comment by dzoanka** [comment]
done and tested
